target: pct_pos_total # nazwa kolumny z targetem

clean:
  threshold_missing: 0.3 # maksymalny akceptowalny procent braków

  platform_cols: # kolumny platform
    - windows
    - mac
    - linux

  drop_cols:
    # leakage: recenzje / wyniki / popularność
    - reviews
    - positive
    - negative
    - num_reviews_total
    - num_reviews_recent
    - pct_pos_recent
    - recommendations
    - user_score
    - score_rank
    - estimated_owners
    - average_playtime_forever
    - average_playtime_2weeks
    - median_playtime_forever
    - median_playtime_2weeks
    - peak_ccu

    - detailed_description
    - about_the_game
    - short_description
    - header_image
    - website
    - support_url
    - support_email
    - metacritic_url
    - notes
    - screenshots
    - movies
    - packages

    # identyfikatory
    - name
    - appid

  # kolumny do multilabel binarizer
  mlb_cols:
    - genres
    - categories
    - tags
    - developers
    - publishers
    - supported_languages
    - full_audio_languages

  top_n_labels: 50 # liczba najpopularniejszych etykiet do zachowania

random_state: 42 # seed losowy

split:
  test_size: 0.2 # wielkość zbioru testowego
  random_state: ${random_state}

model:
  n_estimators: 200 # liczba drzew
  n_jobs: -1 # pełne wykorzystanie cpu
  random_state: ${random_state}

autogluon:
  time_limit: 30 # limit czasu trenowania
  presets: "medium_quality_faster_train" # zestaw presetów
  problem_type: "regression" # typ zadania
  label: ${target}
  eval_metric: "rmse"
  random_state: ${random_state}
